#!/bin/sh
DIR=$1
ROOT_MOUNT=$(awk '$2=="/" {print substr($4,1,2)}' < /etc/fstab)
if [ $ROOT_MOUNT = "rw" ]
then
   /bin/mount --bind /orig/${DIR} ${DIR}
else
   if [ ${DIR} = "/var" ]; then
       /bin/mount -t tmpfs -o size=120m ramdisk ${DIR}_rw
   else 
       /bin/mount -t tmpfs -o size=16m ramdisk ${DIR}_rw
   fi
   /usr/bin/unionfs-fuse -o cow,allow_other,suid,dev,nonempty ${DIR}_rw=RW:/orig/${DIR}=RO ${DIR}
fi
